# Generated by Django 5.2.4 on 2025-08-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_employee_id_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("INACTIVE", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
