# Generated by Django 5.2.4 on 2025-08-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_attendance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={},
        ),
        migrations.AddField(
            model_name="attendance",
            name="scheduled_time_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="scheduled_time_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
