# Generated by Django 5.2.4 on 2025-08-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_birthday_user_contact_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
