# Generated by Django 5.2.4 on 2025-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pagibig",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="philhealth",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sss",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
