# Generated by Django 5.2.4 on 2025-08-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_pagibig_user_philhealth_user_photo_user_sss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, default="photos/default.png", null=True, upload_to="photos/"
            ),
        ),
    ]
