# Generated by Django 5.2.4 on 2025-08-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="scheduled_time_in",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="scheduled_time_out",
        ),
    ]
