# Generated by Django 5.2.4 on 2025-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_overtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overtime",
            name="approved",
        ),
        migrations.AddField(
            model_name="overtime",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="overtime",
            name="date",
            field=models.DateField(),
        ),
    ]
