# Generated by Django 5.2.4 on 2025-08-30 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_overtime_approver_overtime_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overtime",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="overtime",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="overtime",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="overtime",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_overtime",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="overtime",
            name="time_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="overtime",
            name="time_out",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="overtime",
            name="hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="overtime",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
