# Generated by Django 5.2.4 on 2025-08-31 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_remove_overtime_approver_remove_overtime_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
