# Generated by Django 5.2.4 on 2025-09-02 14:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_user_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowances",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
