# Generated by Django 5.2.4 on 2025-09-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_remove_user_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=2,
            ),
            preserve_default=False,
        ),
    ]
