# Generated by Django 5.2.4 on 2025-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_schedule_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (1, "Sun"),
                    (2, "Mon"),
                    (3, "Tue"),
                    (4, "Wed"),
                    (5, "Thu"),
                    (6, "Fri"),
                    (7, "Sat"),
                ]
            ),
        ),
    ]
