# Generated by Django 5.2.4 on 2025-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_schedule_day_of_week"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        choices=[
                            (1, "Sun"),
                            (2, "Mon"),
                            (3, "Tue"),
                            (4, "Wed"),
                            (5, "Thu"),
                            (6, "Fri"),
                            (7, "Sat"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="day_of_week",
        ),
        migrations.AddField(
            model_name="schedule",
            name="days_of_week",
            field=models.ManyToManyField(to="users.day"),
        ),
    ]
