# Generated by Django 5.2.4 on 2025-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_day_remove_schedule_day_of_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[("Half Day", "Half Day"), ("Whole Day", "Whole Day")],
                default="Whole Day",
                max_length=20,
            ),
        ),
    ]
