# Generated by Django 5.2.4 on 2025-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="leave_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
