# Generated by Django 5.2.4 on 2025-09-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_user_leave_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="leave_count",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
