# Generated by Django 5.2.4 on 2025-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_user_leave_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="photos/DefaultPhoto.jpg",
                null=True,
                upload_to="photos/",
            ),
        ),
    ]
