# Generated by Django 5.2.4 on 2025-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_user_photo_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="half_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[("half_day", "Half Day"), ("whole_day", "Whole Day")],
                default="whole_day",
                max_length=10,
            ),
        ),
    ]
