# Generated by Django 5.2.4 on 2025-09-06 15:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_attendance_half_day_alter_leave_leave_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="number",
            field=models.IntegerField(
                choices=[
                    (0, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="leave_count",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("15.0"), max_digits=5
            ),
        ),
    ]
