# Generated by Django 5.2.4 on 2025-09-07 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_schedulechangerequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulechangerequest",
            old_name="requested_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="schedulechangerequest",
            old_name="new_time_in",
            new_name="requested_time_in",
        ),
        migrations.RenameField(
            model_name="schedulechangerequest",
            old_name="new_time_out",
            new_name="requested_time_out",
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_schedule_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="schedule",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="users.schedule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
