# Generated by Django 5.2.4 on 2025-09-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_rename_requested_at_schedulechangerequest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="users.schedule",
            ),
        ),
    ]
