# Generated by Django 5.2.4 on 2025-09-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_employeeschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[("full", "Full Day"), ("half", "Half Day")], max_length=10
            ),
        ),
    ]
