# Generated by Django 5.2.4 on 2025-09-11 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulechangerequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_schedule_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[("half_day", "Half Day"), ("whole_day", "Whole Day")],
                default="whole_day",
                max_length=20,
            ),
        ),
    ]
