# Generated by Django 5.2.4 on 2025-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_schedulechangerequest_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtime",
            name="overtime_type",
            field=models.CharField(
                choices=[
                    ("ordinary", "OT"),
                    ("rest_day", "RD-OT"),
                    ("special_holiday", "SH-OT"),
                    ("special_holiday_rest", "SHRD-OT"),
                    ("regular_holiday", "RH-OT"),
                    ("regular_holiday_rest", "RHRD-OT"),
                    ("double_holiday", "DH-OT"),
                    ("double_holiday_rest", "DHRD-OT"),
                ],
                default="ordinary",
                max_length=30,
            ),
        ),
    ]
