# Generated by Django 5.2.4 on 2025-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_overtime_overtime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtime",
            name="overtime_type",
            field=models.CharField(
                choices=[
                    ("ordinary", "Ordinary Day"),
                    ("restday", "Rest Day"),
                    ("special_holiday", "Special Holiday"),
                    ("special_holiday_restday", "Special Holiday + Rest Day"),
                    ("regular_holiday", "Regular Holiday"),
                    ("regular_holiday_restday", "Regular Holiday + Rest Day"),
                    ("double_holiday", "Double Holiday"),
                    ("double_holiday_restday", "Double Holiday + Rest Day"),
                ],
                default="ordinary",
                max_length=30,
            ),
        ),
    ]
