# Generated by Django 5.2.4 on 2025-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_alter_overtime_overtime_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtime",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
