# Generated by Django 5.2.4 on 2025-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_leave_updated_at_alter_leave_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="leave",
            name="reason",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
