# Generated by Django 5.2.4 on 2025-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_remove_leave_updated_at_alter_leave_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
