# Generated by Django 5.2.4 on 2025-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_user_session_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="session_key",
            new_name="current_session_key",
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
