# Generated by Django 5.2.4 on 2025-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_rename_session_key_user_current_session_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_seen",
        ),
        migrations.AddField(
            model_name="user",
            name="last_session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
