# Generated by Django 5.2.4 on 2025-09-18 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_remove_user_last_seen_user_last_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
