# Generated by Django 5.2.4 on 2025-09-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_user_login_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="current_session_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_session_key",
        ),
    ]
