# Generated by Django 5.2.4 on 2025-09-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_remove_user_current_session_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
    ]
