# Generated by Django 5.2.4 on 2025-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
    ]
