# Generated by Django 5.2.4 on 2025-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_months",
            field=models.PositiveIntegerField(
                choices=[(12, "12 Months"), (18, "18 Months"), (24, "24 Months")],
                default=12,
            ),
        ),
    ]
