# Generated by Django 5.2.4 on 2025-10-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_loan_end_date_loan_term_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
