# Generated by Django 5.2.4 on 2025-10-04 09:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_alter_loan_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="loan_deduct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Semi-monthly deduction amount applied to this loan.",
                max_digits=12,
            ),
        ),
    ]
