# Generated by Django 5.2.4 on 2025-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0057_loan_loan_deduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="loan_type_summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
