# Generated by Django 5.2.4 on 2025-10-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0058_loan_loan_type_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="amount",
            new_name="loan_amount",
        ),
    ]
