# Generated by Django 5.2.4 on 2025-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0059_rename_amount_loan_loan_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
