# Generated by Django 5.2.4 on 2025-10-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0060_user_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
    ]
