# Generated by Django 5.2.4 on 2025-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_announcement_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for the announcement.",
                null=True,
                upload_to="announcements/",
            ),
        ),
    ]
