# Generated by Django 5.2.4 on 2025-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="period",
            field=models.CharField(
                choices=[("first_half", "1st Half"), ("second_half", "2nd Half")],
                default=2,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
