# Generated by Django 5.2.4 on 2025-09-05 14:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_payroll_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payroll",
            name="unique_payroll_per_employee_per_month",
        ),
        migrations.AddField(
            model_name="payroll",
            name="holiday_pay",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="overtime_pay",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.UniqueConstraint(
                fields=("employee", "month", "year", "period"),
                name="unique_payroll_per_employee_per_period",
            ),
        ),
    ]
