# Generated by Django 5.2.4 on 2025-08-31 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_payroll_delete_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
