# Generated by Django 5.2.4 on 2025-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_payroll_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
