# Generated by Django 5.2.4 on 2025-09-12 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0003_remove_payroll_unique_payroll_per_employee_per_month_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
