# Generated by Django 5.2.4 on 2025-09-12 19:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_payroll_daily_rate_payroll_hourly_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="overtime_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.25"), max_digits=5
            ),
        ),
    ]
