# Generated by Django 5.2.4 on 2025-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_payroll_overtime_hours_payroll_overtime_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="overtime_rate",
        ),
        migrations.AddField(
            model_name="payroll",
            name="overtime_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ordinary", "Ordinary Day"),
                    ("restday", "Rest Day"),
                    ("special_holiday", "Special Holiday"),
                    ("special_holiday_restday", "Special Holiday + Rest Day"),
                    ("regular_holiday", "Regular Holiday"),
                    ("regular_holiday_restday", "Regular Holiday + Rest Day"),
                    ("double_holiday", "Double Holiday"),
                    ("double_holiday_restday", "Double Holiday + Rest Day"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
