# Generated by Django 5.2.4 on 2025-09-18 18:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_remove_payroll_overtime_rate_payroll_overtime_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="attendance_deduction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
