# Generated by Django 5.2.4 on 2025-09-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_payroll_attendance_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="attendance_breakdown",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
