# Generated by Django 5.2.4 on 2025-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_payroll_attendance_breakdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="attendance_breakdown",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
