# Generated by Django 5.2.4 on 2025-10-04 09:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0009_alter_payroll_attendance_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="loan_deduction",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
