# Generated by Django 5.2.4 on 2025-10-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_payroll_loan_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="loan_type_summary",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
