# Generated by Django 5.2.4 on 2025-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_payroll_loan_type_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payroll",
            name="loan_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
